sudo: required
language: java

notifications:
    email: false

services:
  - docker

before_install:
- docker pull apcera/gnatsd
- docker run -d -p 4222:4222 -p 8333:8333 apcera/gnatsd
- docker ps -a
