package cz.sohlich.natsproxy.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

public final class Protobuf {
    private Protobuf() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface ValuesOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Values)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated string arr = 1;</code>
         */
        com.google.protobuf.ProtocolStringList
        getArrList();

        /**
         * <code>repeated string arr = 1;</code>
         */
        int getArrCount();

        /**
         * <code>repeated string arr = 1;</code>
         */
        java.lang.String getArr(int index);

        /**
         * <code>repeated string arr = 1;</code>
         */
        com.google.protobuf.ByteString
        getArrBytes(int index);
    }

    /**
     * Protobuf type {@code Values}
     */
    public static final class Values extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:Values)
            ValuesOrBuilder {
        // Use Values.newBuilder() to construct.
        private Values(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Values() {
            arr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Protobuf.internal_static_Values_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Protobuf.internal_static_Values_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Protobuf.Values.class, Protobuf.Values.Builder.class);
        }

        public static final int ARR_FIELD_NUMBER = 1;
        private com.google.protobuf.LazyStringList arr_;

        /**
         * <code>repeated string arr = 1;</code>
         */
        public com.google.protobuf.ProtocolStringList
        getArrList() {
            return arr_;
        }

        /**
         * <code>repeated string arr = 1;</code>
         */
        public int getArrCount() {
            return arr_.size();
        }

        /**
         * <code>repeated string arr = 1;</code>
         */
        public java.lang.String getArr(int index) {
            return arr_.get(index);
        }

        /**
         * <code>repeated string arr = 1;</code>
         */
        public com.google.protobuf.ByteString
        getArrBytes(int index) {
            return arr_.getByteString(index);
        }

        public static Protobuf.Values parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Protobuf.Values parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Protobuf.Values parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Protobuf.Values parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Protobuf.Values parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Protobuf.Values parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Protobuf.Values parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static Protobuf.Values parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static Protobuf.Values parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Protobuf.Values parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Protobuf.Values prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Values}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Values)
                Protobuf.ValuesOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Protobuf.internal_static_Values_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Protobuf.internal_static_Values_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Protobuf.Values.class, Protobuf.Values.Builder.class);
            }

            // Construct using Protobuf.Values.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                arr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Protobuf.internal_static_Values_descriptor;
            }

            public Protobuf.Values getDefaultInstanceForType() {
                return Protobuf.Values.getDefaultInstance();
            }

            public Protobuf.Values build() {
                Protobuf.Values result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Protobuf.Values buildPartial() {
                Protobuf.Values result = new Protobuf.Values(this);
                int from_bitField0_ = bitField0_;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    arr_ = arr_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.arr_ = arr_;
                onBuilt();
                return result;
            }

            private int bitField0_;

            private com.google.protobuf.LazyStringList arr_ = com.google.protobuf.LazyStringArrayList.EMPTY;

            private void ensureArrIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    arr_ = new com.google.protobuf.LazyStringArrayList(arr_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated string arr = 1;</code>
             */
            public com.google.protobuf.ProtocolStringList
            getArrList() {
                return arr_.getUnmodifiableView();
            }

            /**
             * <code>repeated string arr = 1;</code>
             */
            public int getArrCount() {
                return arr_.size();
            }

            /**
             * <code>repeated string arr = 1;</code>
             */
            public java.lang.String getArr(int index) {
                return arr_.get(index);
            }

            /**
             * <code>repeated string arr = 1;</code>
             */
            public com.google.protobuf.ByteString
            getArrBytes(int index) {
                return arr_.getByteString(index);
            }

            /**
             * <code>repeated string arr = 1;</code>
             */
            public Builder setArr(
                    int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureArrIsMutable();
                arr_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string arr = 1;</code>
             */
            public Builder addArr(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureArrIsMutable();
                arr_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string arr = 1;</code>
             */
            public Builder addAllArr(
                    java.lang.Iterable<java.lang.String> values) {
                ensureArrIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, arr_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string arr = 1;</code>
             */
            public Builder clearArr() {
                arr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string arr = 1;</code>
             */
            public Builder addArrBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                ensureArrIsMutable();
                arr_.add(value);
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:Values)
        }

        // @@protoc_insertion_point(class_scope:Values)
        private static final Protobuf.Values DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Protobuf.Values();
        }

        public static Protobuf.Values getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Values>
                PARSER = new com.google.protobuf.AbstractParser<Values>() {
            public Values parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e.getMessage()).setUnfinishedMessage(
                            builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Values> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Values> getParserForType() {
            return PARSER;
        }

        public Protobuf.Values getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface RequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Request)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string URL = 1;</code>
         */
        java.lang.String getURL();

        /**
         * <code>optional string URL = 1;</code>
         */
        com.google.protobuf.ByteString
        getURLBytes();

        /**
         * <code>optional string Method = 2;</code>
         */
        java.lang.String getMethod();

        /**
         * <code>optional string Method = 2;</code>
         */
        com.google.protobuf.ByteString
        getMethodBytes();

        /**
         * <code>optional string RemoteAddr = 3;</code>
         */
        java.lang.String getRemoteAddr();

        /**
         * <code>optional string RemoteAddr = 3;</code>
         */
        com.google.protobuf.ByteString
        getRemoteAddrBytes();

        /**
         * <code>optional bytes Body = 4;</code>
         */
        com.google.protobuf.ByteString getBody();

        /**
         * <code>map&lt;string, .Values&gt; Form = 5;</code>
         */
        java.util.Map<java.lang.String, Protobuf.Values>
        getForm();

        /**
         * <code>map&lt;string, .Values&gt; Header = 6;</code>
         */
        java.util.Map<java.lang.String, Protobuf.Values>
        getHeader();

        /**
         * <code>optional string WebSocketID = 7;</code>
         */
        java.lang.String getWebSocketID();

        /**
         * <code>optional string WebSocketID = 7;</code>
         */
        com.google.protobuf.ByteString
        getWebSocketIDBytes();
    }

    /**
     * Protobuf type {@code Request}
     */
    public static final class Request extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:Request)
            RequestOrBuilder {
        // Use Request.newBuilder() to construct.
        private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Request() {
            uRL_ = "";
            method_ = "";
            remoteAddr_ = "";
            body_ = com.google.protobuf.ByteString.EMPTY;
            webSocketID_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Protobuf.internal_static_Request_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 5:
                    return internalGetForm();
                case 6:
                    return internalGetHeader();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Protobuf.internal_static_Request_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Protobuf.Request.class, Protobuf.Request.Builder.class);
        }

        private int bitField0_;
        public static final int URL_FIELD_NUMBER = 1;
        private volatile java.lang.Object uRL_;

        /**
         * <code>optional string URL = 1;</code>
         */
        public java.lang.String getURL() {
            java.lang.Object ref = uRL_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                uRL_ = s;
                return s;
            }
        }

        /**
         * <code>optional string URL = 1;</code>
         */
        public com.google.protobuf.ByteString
        getURLBytes() {
            java.lang.Object ref = uRL_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                uRL_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int METHOD_FIELD_NUMBER = 2;
        private volatile java.lang.Object method_;

        /**
         * <code>optional string Method = 2;</code>
         */
        public java.lang.String getMethod() {
            java.lang.Object ref = method_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                method_ = s;
                return s;
            }
        }

        /**
         * <code>optional string Method = 2;</code>
         */
        public com.google.protobuf.ByteString
        getMethodBytes() {
            java.lang.Object ref = method_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                method_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int REMOTEADDR_FIELD_NUMBER = 3;
        private volatile java.lang.Object remoteAddr_;

        /**
         * <code>optional string RemoteAddr = 3;</code>
         */
        public java.lang.String getRemoteAddr() {
            java.lang.Object ref = remoteAddr_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                remoteAddr_ = s;
                return s;
            }
        }

        /**
         * <code>optional string RemoteAddr = 3;</code>
         */
        public com.google.protobuf.ByteString
        getRemoteAddrBytes() {
            java.lang.Object ref = remoteAddr_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                remoteAddr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BODY_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString body_;

        /**
         * <code>optional bytes Body = 4;</code>
         */
        public com.google.protobuf.ByteString getBody() {
            return body_;
        }

        public static final int FORM_FIELD_NUMBER = 5;

        private static final class FormDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, Protobuf.Values> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, Protobuf.Values>newDefaultInstance(
                                    Protobuf.internal_static_Request_FormEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.MESSAGE,
                                    Protobuf.Values.getDefaultInstance());
        }

        private com.google.protobuf.MapField<
                java.lang.String, Protobuf.Values> form_;

        private com.google.protobuf.MapField<java.lang.String, Protobuf.Values>
        internalGetForm() {
            if (form_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        FormDefaultEntryHolder.defaultEntry);
            }
            return form_;
        }

        /**
         * <code>map&lt;string, .Values&gt; Form = 5;</code>
         */

        public java.util.Map<java.lang.String, Protobuf.Values> getForm() {
            return internalGetForm().getMap();
        }

        public static final int HEADER_FIELD_NUMBER = 6;

        private static final class HeaderDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, Protobuf.Values> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, Protobuf.Values>newDefaultInstance(
                                    Protobuf.internal_static_Request_HeaderEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.MESSAGE,
                                    Protobuf.Values.getDefaultInstance());
        }

        private com.google.protobuf.MapField<
                java.lang.String, Protobuf.Values> header_;

        private com.google.protobuf.MapField<java.lang.String, Protobuf.Values>
        internalGetHeader() {
            if (header_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        HeaderDefaultEntryHolder.defaultEntry);
            }
            return header_;
        }

        /**
         * <code>map&lt;string, .Values&gt; Header = 6;</code>
         */

        public java.util.Map<java.lang.String, Protobuf.Values> getHeader() {
            return internalGetHeader().getMap();
        }

        public static final int WEBSOCKETID_FIELD_NUMBER = 7;
        private volatile java.lang.Object webSocketID_;

        /**
         * <code>optional string WebSocketID = 7;</code>
         */
        public java.lang.String getWebSocketID() {
            java.lang.Object ref = webSocketID_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                webSocketID_ = s;
                return s;
            }
        }

        /**
         * <code>optional string WebSocketID = 7;</code>
         */
        public com.google.protobuf.ByteString
        getWebSocketIDBytes() {
            java.lang.Object ref = webSocketID_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                webSocketID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static Protobuf.Request parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Protobuf.Request parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Protobuf.Request parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Protobuf.Request parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Protobuf.Request parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Protobuf.Request parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Protobuf.Request parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static Protobuf.Request parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static Protobuf.Request parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Protobuf.Request parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Protobuf.Request prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Request}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Request)
                Protobuf.RequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Protobuf.internal_static_Request_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 5:
                        return internalGetForm();
                    case 6:
                        return internalGetHeader();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 5:
                        return internalGetMutableForm();
                    case 6:
                        return internalGetMutableHeader();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Protobuf.internal_static_Request_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Protobuf.Request.class, Protobuf.Request.Builder.class);
            }

            // Construct using Protobuf.Request.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                uRL_ = "";

                method_ = "";

                remoteAddr_ = "";

                body_ = com.google.protobuf.ByteString.EMPTY;

                internalGetMutableForm().clear();
                internalGetMutableHeader().clear();
                webSocketID_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Protobuf.internal_static_Request_descriptor;
            }

            public Protobuf.Request getDefaultInstanceForType() {
                return Protobuf.Request.getDefaultInstance();
            }

            public Protobuf.Request build() {
                Protobuf.Request result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Protobuf.Request buildPartial() {
                Protobuf.Request result = new Protobuf.Request(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.uRL_ = uRL_;
                result.method_ = method_;
                result.remoteAddr_ = remoteAddr_;
                result.body_ = body_;
                result.form_ = internalGetForm();
                result.form_.makeImmutable();
                result.header_ = internalGetHeader();
                result.header_.makeImmutable();
                result.webSocketID_ = webSocketID_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            private int bitField0_;

            private java.lang.Object uRL_ = "";

            /**
             * <code>optional string URL = 1;</code>
             */
            public java.lang.String getURL() {
                java.lang.Object ref = uRL_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    uRL_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string URL = 1;</code>
             */
            public com.google.protobuf.ByteString
            getURLBytes() {
                java.lang.Object ref = uRL_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    uRL_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string URL = 1;</code>
             */
            public Builder setURL(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                uRL_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string URL = 1;</code>
             */
            public Builder clearURL() {

                uRL_ = getDefaultInstance().getURL();
                onChanged();
                return this;
            }

            /**
             * <code>optional string URL = 1;</code>
             */
            public Builder setURLBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                uRL_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object method_ = "";

            /**
             * <code>optional string Method = 2;</code>
             */
            public java.lang.String getMethod() {
                java.lang.Object ref = method_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    method_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string Method = 2;</code>
             */
            public com.google.protobuf.ByteString
            getMethodBytes() {
                java.lang.Object ref = method_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    method_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string Method = 2;</code>
             */
            public Builder setMethod(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                method_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string Method = 2;</code>
             */
            public Builder clearMethod() {

                method_ = getDefaultInstance().getMethod();
                onChanged();
                return this;
            }

            /**
             * <code>optional string Method = 2;</code>
             */
            public Builder setMethodBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                method_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object remoteAddr_ = "";

            /**
             * <code>optional string RemoteAddr = 3;</code>
             */
            public java.lang.String getRemoteAddr() {
                java.lang.Object ref = remoteAddr_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    remoteAddr_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string RemoteAddr = 3;</code>
             */
            public com.google.protobuf.ByteString
            getRemoteAddrBytes() {
                java.lang.Object ref = remoteAddr_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    remoteAddr_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string RemoteAddr = 3;</code>
             */
            public Builder setRemoteAddr(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                remoteAddr_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string RemoteAddr = 3;</code>
             */
            public Builder clearRemoteAddr() {

                remoteAddr_ = getDefaultInstance().getRemoteAddr();
                onChanged();
                return this;
            }

            /**
             * <code>optional string RemoteAddr = 3;</code>
             */
            public Builder setRemoteAddrBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                remoteAddr_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>optional bytes Body = 4;</code>
             */
            public com.google.protobuf.ByteString getBody() {
                return body_;
            }

            /**
             * <code>optional bytes Body = 4;</code>
             */
            public Builder setBody(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                body_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes Body = 4;</code>
             */
            public Builder clearBody() {

                body_ = getDefaultInstance().getBody();
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<
                    java.lang.String, Protobuf.Values> form_;

            private com.google.protobuf.MapField<java.lang.String, Protobuf.Values>
            internalGetForm() {
                if (form_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            FormDefaultEntryHolder.defaultEntry);
                }
                return form_;
            }

            private com.google.protobuf.MapField<java.lang.String, Protobuf.Values>
            internalGetMutableForm() {
                onChanged();
                ;
                if (form_ == null) {
                    form_ = com.google.protobuf.MapField.newMapField(
                            FormDefaultEntryHolder.defaultEntry);
                }
                if (!form_.isMutable()) {
                    form_ = form_.copy();
                }
                return form_;
            }

            /**
             * <code>map&lt;string, .Values&gt; Form = 5;</code>
             */
            public java.util.Map<java.lang.String, Protobuf.Values> getForm() {
                return internalGetForm().getMap();
            }

            /**
             * <code>map&lt;string, .Values&gt; Form = 5;</code>
             */
            public java.util.Map<java.lang.String, Protobuf.Values>
            getMutableForm() {
                return internalGetMutableForm().getMutableMap();
            }

            /**
             * <code>map&lt;string, .Values&gt; Form = 5;</code>
             */
            public Builder putAllForm(
                    java.util.Map<java.lang.String, Protobuf.Values> values) {
                getMutableForm().putAll(values);
                return this;
            }

            private com.google.protobuf.MapField<
                    java.lang.String, Protobuf.Values> header_;

            private com.google.protobuf.MapField<java.lang.String, Protobuf.Values>
            internalGetHeader() {
                if (header_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            HeaderDefaultEntryHolder.defaultEntry);
                }
                return header_;
            }

            private com.google.protobuf.MapField<java.lang.String, Protobuf.Values>
            internalGetMutableHeader() {
                onChanged();
                ;
                if (header_ == null) {
                    header_ = com.google.protobuf.MapField.newMapField(
                            HeaderDefaultEntryHolder.defaultEntry);
                }
                if (!header_.isMutable()) {
                    header_ = header_.copy();
                }
                return header_;
            }

            /**
             * <code>map&lt;string, .Values&gt; Header = 6;</code>
             */
            public java.util.Map<java.lang.String, Protobuf.Values> getHeader() {
                return internalGetHeader().getMap();
            }

            /**
             * <code>map&lt;string, .Values&gt; Header = 6;</code>
             */
            public java.util.Map<java.lang.String, Protobuf.Values>
            getMutableHeader() {
                return internalGetMutableHeader().getMutableMap();
            }

            /**
             * <code>map&lt;string, .Values&gt; Header = 6;</code>
             */
            public Builder putAllHeader(
                    java.util.Map<java.lang.String, Protobuf.Values> values) {
                getMutableHeader().putAll(values);
                return this;
            }

            private java.lang.Object webSocketID_ = "";

            /**
             * <code>optional string WebSocketID = 7;</code>
             */
            public java.lang.String getWebSocketID() {
                java.lang.Object ref = webSocketID_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    webSocketID_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string WebSocketID = 7;</code>
             */
            public com.google.protobuf.ByteString
            getWebSocketIDBytes() {
                java.lang.Object ref = webSocketID_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    webSocketID_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string WebSocketID = 7;</code>
             */
            public Builder setWebSocketID(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                webSocketID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string WebSocketID = 7;</code>
             */
            public Builder clearWebSocketID() {

                webSocketID_ = getDefaultInstance().getWebSocketID();
                onChanged();
                return this;
            }

            /**
             * <code>optional string WebSocketID = 7;</code>
             */
            public Builder setWebSocketIDBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                webSocketID_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:Request)
        }

        // @@protoc_insertion_point(class_scope:Request)
        private static final Protobuf.Request DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Protobuf.Request();
        }

        public static Protobuf.Request getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Request>
                PARSER = new com.google.protobuf.AbstractParser<Request>() {
            public Request parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e.getMessage()).setUnfinishedMessage(
                            builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Request> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Request> getParserForType() {
            return PARSER;
        }

        public Protobuf.Request getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Response)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional int32 StatusCode = 1;</code>
         */
        int getStatusCode();

        /**
         * <code>map&lt;string, .Values&gt; Header = 2;</code>
         */
        java.util.Map<java.lang.String, Protobuf.Values>
        getHeader();

        /**
         * <code>optional bytes Body = 3;</code>
         */
        com.google.protobuf.ByteString getBody();

        /**
         * <code>optional bool DoUpgrade = 4;</code>
         */
        boolean getDoUpgrade();
    }

    /**
     * Protobuf type {@code Response}
     */
    public static final class Response extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:Response)
            ResponseOrBuilder {
        // Use Response.newBuilder() to construct.
        private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Response() {
            statusCode_ = 0;
            body_ = com.google.protobuf.ByteString.EMPTY;
            doUpgrade_ = false;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Protobuf.internal_static_Response_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 2:
                    return internalGetHeader();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Protobuf.internal_static_Response_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Protobuf.Response.class, Protobuf.Response.Builder.class);
        }

        private int bitField0_;
        public static final int STATUSCODE_FIELD_NUMBER = 1;
        private int statusCode_;

        /**
         * <code>optional int32 StatusCode = 1;</code>
         */
        public int getStatusCode() {
            return statusCode_;
        }

        public static final int HEADER_FIELD_NUMBER = 2;

        private static final class HeaderDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, Protobuf.Values> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, Protobuf.Values>newDefaultInstance(
                                    Protobuf.internal_static_Response_HeaderEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.MESSAGE,
                                    Protobuf.Values.getDefaultInstance());
        }

        private com.google.protobuf.MapField<
                java.lang.String, Protobuf.Values> header_;

        private com.google.protobuf.MapField<java.lang.String, Protobuf.Values>
        internalGetHeader() {
            if (header_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        HeaderDefaultEntryHolder.defaultEntry);
            }
            return header_;
        }

        /**
         * <code>map&lt;string, .Values&gt; Header = 2;</code>
         */

        public java.util.Map<java.lang.String, Protobuf.Values> getHeader() {
            return internalGetHeader().getMap();
        }

        public static final int BODY_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString body_;

        /**
         * <code>optional bytes Body = 3;</code>
         */
        public com.google.protobuf.ByteString getBody() {
            return body_;
        }

        public static final int DOUPGRADE_FIELD_NUMBER = 4;
        private boolean doUpgrade_;

        /**
         * <code>optional bool DoUpgrade = 4;</code>
         */
        public boolean getDoUpgrade() {
            return doUpgrade_;
        }

        public static Protobuf.Response parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Protobuf.Response parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Protobuf.Response parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Protobuf.Response parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Protobuf.Response parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Protobuf.Response parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Protobuf.Response parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static Protobuf.Response parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static Protobuf.Response parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Protobuf.Response parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Protobuf.Response prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Response}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Response)
                Protobuf.ResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Protobuf.internal_static_Response_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 2:
                        return internalGetHeader();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 2:
                        return internalGetMutableHeader();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Protobuf.internal_static_Response_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Protobuf.Response.class, Protobuf.Response.Builder.class);
            }

            // Construct using Protobuf.Response.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                statusCode_ = 0;

                internalGetMutableHeader().clear();
                body_ = com.google.protobuf.ByteString.EMPTY;

                doUpgrade_ = false;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Protobuf.internal_static_Response_descriptor;
            }

            public Protobuf.Response getDefaultInstanceForType() {
                return Protobuf.Response.getDefaultInstance();
            }

            public Protobuf.Response build() {
                Protobuf.Response result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Protobuf.Response buildPartial() {
                Protobuf.Response result = new Protobuf.Response(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.statusCode_ = statusCode_;
                result.header_ = internalGetHeader();
                result.header_.makeImmutable();
                result.body_ = body_;
                result.doUpgrade_ = doUpgrade_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            private int bitField0_;

            private int statusCode_;

            /**
             * <code>optional int32 StatusCode = 1;</code>
             */
            public int getStatusCode() {
                return statusCode_;
            }

            /**
             * <code>optional int32 StatusCode = 1;</code>
             */
            public Builder setStatusCode(int value) {

                statusCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 StatusCode = 1;</code>
             */
            public Builder clearStatusCode() {

                statusCode_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<
                    java.lang.String, Protobuf.Values> header_;

            private com.google.protobuf.MapField<java.lang.String, Protobuf.Values>
            internalGetHeader() {
                if (header_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            HeaderDefaultEntryHolder.defaultEntry);
                }
                return header_;
            }

            private com.google.protobuf.MapField<java.lang.String, Protobuf.Values>
            internalGetMutableHeader() {
                onChanged();
                ;
                if (header_ == null) {
                    header_ = com.google.protobuf.MapField.newMapField(
                            HeaderDefaultEntryHolder.defaultEntry);
                }
                if (!header_.isMutable()) {
                    header_ = header_.copy();
                }
                return header_;
            }

            /**
             * <code>map&lt;string, .Values&gt; Header = 2;</code>
             */
            public java.util.Map<java.lang.String, Protobuf.Values> getHeader() {
                return internalGetHeader().getMap();
            }

            /**
             * <code>map&lt;string, .Values&gt; Header = 2;</code>
             */
            public java.util.Map<java.lang.String, Protobuf.Values>
            getMutableHeader() {
                return internalGetMutableHeader().getMutableMap();
            }

            /**
             * <code>map&lt;string, .Values&gt; Header = 2;</code>
             */
            public Builder putAllHeader(
                    java.util.Map<java.lang.String, Protobuf.Values> values) {
                getMutableHeader().putAll(values);
                return this;
            }

            private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>optional bytes Body = 3;</code>
             */
            public com.google.protobuf.ByteString getBody() {
                return body_;
            }

            /**
             * <code>optional bytes Body = 3;</code>
             */
            public Builder setBody(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                body_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes Body = 3;</code>
             */
            public Builder clearBody() {

                body_ = getDefaultInstance().getBody();
                onChanged();
                return this;
            }

            private boolean doUpgrade_;

            /**
             * <code>optional bool DoUpgrade = 4;</code>
             */
            public boolean getDoUpgrade() {
                return doUpgrade_;
            }

            /**
             * <code>optional bool DoUpgrade = 4;</code>
             */
            public Builder setDoUpgrade(boolean value) {

                doUpgrade_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool DoUpgrade = 4;</code>
             */
            public Builder clearDoUpgrade() {

                doUpgrade_ = false;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:Response)
        }

        // @@protoc_insertion_point(class_scope:Response)
        private static final Protobuf.Response DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Protobuf.Response();
        }

        public static Protobuf.Response getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Response>
                PARSER = new com.google.protobuf.AbstractParser<Response>() {
            public Response parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e.getMessage()).setUnfinishedMessage(
                            builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Response> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Response> getParserForType() {
            return PARSER;
        }

        public Protobuf.Response getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Values_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Values_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Request_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Request_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Request_FormEntry_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Request_FormEntry_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Request_HeaderEntry_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Request_HeaderEntry_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Response_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Response_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Response_HeaderEntry_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Response_HeaderEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\016protobuf.proto\"\025\n\006Values\022\013\n\003arr\030\001 \003(\t\"" +
                        "\223\002\n\007Request\022\013\n\003URL\030\001 \001(\t\022\016\n\006Method\030\002 \001(\t" +
                        "\022\022\n\nRemoteAddr\030\003 \001(\t\022\014\n\004Body\030\004 \001(\014\022 \n\004Fo" +
                        "rm\030\005 \003(\0132\022.Request.FormEntry\022$\n\006Header\030\006" +
                        " \003(\0132\024.Request.HeaderEntry\022\023\n\013WebSocketI" +
                        "D\030\007 \001(\t\0324\n\tFormEntry\022\013\n\003key\030\001 \001(\t\022\026\n\005val" +
                        "ue\030\002 \001(\0132\007.Values:\0028\001\0326\n\013HeaderEntry\022\013\n\003" +
                        "key\030\001 \001(\t\022\026\n\005value\030\002 \001(\0132\007.Values:\0028\001\"\236\001" +
                        "\n\010Response\022\022\n\nStatusCode\030\001 \001(\005\022%\n\006Header" +
                        "\030\002 \003(\0132\025.Response.HeaderEntry\022\014\n\004Body\030\003 ",
                "\001(\014\022\021\n\tDoUpgrade\030\004 \001(\010\0326\n\013HeaderEntry\022\013\n" +
                        "\003key\030\001 \001(\t\022\026\n\005value\030\002 \001(\0132\007.Values:\0028\001B\r" +
                        "H\002Z\tnatsproxyb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_Values_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Values_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Values_descriptor,
                new java.lang.String[]{"Arr",});
        internal_static_Request_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_Request_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Request_descriptor,
                new java.lang.String[]{"URL", "Method", "RemoteAddr", "Body", "Form", "Header", "WebSocketID",});
        internal_static_Request_FormEntry_descriptor =
                internal_static_Request_descriptor.getNestedTypes().get(0);
        internal_static_Request_FormEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Request_FormEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
        internal_static_Request_HeaderEntry_descriptor =
                internal_static_Request_descriptor.getNestedTypes().get(1);
        internal_static_Request_HeaderEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Request_HeaderEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
        internal_static_Response_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_Response_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Response_descriptor,
                new java.lang.String[]{"StatusCode", "Header", "Body", "DoUpgrade",});
        internal_static_Response_HeaderEntry_descriptor =
                internal_static_Response_descriptor.getNestedTypes().get(0);
        internal_static_Response_HeaderEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Response_HeaderEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
